import {IoSchoolOutline} from 'react-icons/io5'
import {defineType} from 'sanity'

export const homeSchool = defineType({
  name: 'homeSchool',
  title: '首頁推薦語言學校',
  type: 'document',
  icon: IoSchoolOutline,
  fields: [
    {
      name: 'mainImage',
      title: '封面圖片',
      type: 'image',
      options: {
        hotspot: true,
      },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: '圖片描述',
        },
      ],
    },
    {
      name: 'name',
      title: '學校名稱',
      type: 'string',
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: '與學校列表中的slug相同，請勿更改，否則會導致首頁連結錯誤',
      options: {
        source: 'title',
        maxLength: 96,
      },
    },
    {
      name: 'city',
      title: '地點（縣市）',
      type: 'string',
      options: {
        list: [
          {title: '-----北海道・東北地區-----', value: 'null'},
          {title: '北海道', value: '北海道'},
          {title: '青森縣', value: '青森縣'},
          {title: '岩手縣', value: '岩手縣'},
          {title: '宮城縣', value: '宮城縣'},
          {title: '秋田縣', value: '秋田縣'},
          {title: '山形縣', value: '山形縣'},
          {title: '福島縣', value: '福島縣'},
          {title: '-----關東地區-----', value: ' null'},
          {title: '茨城縣', value: '茨城縣'},
          {title: '栃木縣', value: '栃木縣'},
          {title: '群馬縣', value: '群馬縣'},
          {title: '埼玉縣', value: '埼玉縣'},
          {title: '千葉縣', value: '千葉縣'},
          {title: '東京都', value: '東京都'},
          {title: '神奈川縣', value: '神奈川縣'},
          {title: '-----中部地區-----', value: 'null'},
          {title: '新潟縣', value: '新潟縣'},
          {title: '富山縣', value: '富山縣'},
          {title: '石川縣', value: '石川縣'},
          {title: '福井縣', value: '福井縣'},
          {title: '山梨縣', value: '山梨縣'},
          {title: '長野縣', value: '長野縣'},
          {title: '岐阜縣', value: '岐阜縣'},
          {title: '靜岡縣', value: '靜岡縣'},
          {title: '愛知縣', value: '愛知縣'},
          {title: '-----近畿地區-----', value: 'null'},
          {title: '三重縣', value: '三重縣'},
          {title: '滋賀縣', value: '滋賀縣'},
          {title: '京都府', value: '京都府'},
          {title: '大阪府', value: '大阪府'},
          {title: '兵庫縣', value: '兵庫縣'},
          {title: '奈良縣', value: '奈良縣'},
          {title: '和歌山縣', value: '和歌山縣'},
          {title: '-----中國・四國地區-----', value: 'null'},
          {title: '鳥取縣', value: '鳥取縣'},
          {title: '島根縣', value: '島根縣'},
          {title: '岡山縣', value: '岡山縣'},
          {title: '廣島縣', value: '廣島縣'},
          {title: '山口縣', value: '山口縣'},
          {title: '德島縣', value: '德島縣'},
          {title: '香川縣', value: '香川縣'},
          {title: '愛媛縣', value: '愛媛縣'},
          {title: '高知縣', value: '高知縣'},
          {title: '-----九州・沖繩地區-----', value: 'null'},
          {title: '福岡縣', value: '福岡縣'},
          {title: '佐賀縣', value: '佐賀縣'},
          {title: '長崎縣', value: '長崎縣'},
          {title: '熊本縣', value: '熊本縣'},
          {title: '大分縣', value: '大分縣'},
          {title: '宮崎縣', value: '宮崎縣'},
          {title: '鹿兒島縣', value: '鹿兒島縣'},
          {title: '沖繩縣', value: '沖繩縣'},
        ],
      },
    },
    {
      name: 'transportation',
      title: '交通',
      type: 'text',
      description: '統一寫「某某站徒步00分鐘」的格式，什麼線不用寫',
    },
    {
      name: 'description',
      title: '學校簡介',
      type: 'text',
      description: '盡可能的濃縮，精簡成132字以內（包含標點符號）否則會影響版面',
      validation: (Rule) => Rule.max(132).warning('學校簡介不能超過132個字'),
    },
    {
      name: 'character',
      title: '學校特色',
      type: 'text',
      description: '寫一兩個最重要的就好，否則會影響版面',
    },
  ],
})
